# SAP particulars
# Enter the components and views as comma listed params.
protocol: ""
host: ""
port: 
username: ""
password: ""
component: ""
view: ""
metricPathPrefix: "Custom Metrics|SAP|"